### ISSUE TITLE
Make Paginator more bootstraps flexible

### ISSUE THREAD

**Issue by Dandanov** [alexSivka/php-paginator#1]
1. it would be great have possible to customize Paginator - center, left, right, small, big, as a native bootstrap. 
2. Today we have 4.5 Bootstrpap. Paginator work, but what if tomorow...

we can do it byouselves, but it's not good practice

in any case thank you

**Comment by alexSivka** [comment]
You are right. Think how to implement this right  way. 
Идея понятна. Надо подумать как это реализовать с минимум костылей )).

**Comment by alexSivka** [comment]
Feature added. See https://github.com/alexSivka/php-paginator#dimensions

**Comment by Dandanov** [comment]
that's good! Отлично!
